# Generated by Django 5.2.1 on 2025-06-01 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
